spring.application.name=open-ecom
# ==============================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# ==============================
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/openecom?useSSL=false&serverTimezone=UTC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=Rohan
spring.datasource.password=HareKrishna@12
# ============================
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
logging.level.org.springframework.security=DEBUG